<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Calcolb.Modules.Event.Domain\Calcolb.Modules.Event.Domain.csproj" />
    <ProjectReference Include="..\Calcolb.Modules.Event.Application\Calcolb.Modules.Event.Application.csproj" />
    <ProjectReference Include="..\..\..\Calcolb.Shared\Calcolb.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="*" />
    <PackageReference Include="Serilog" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
